### ISSUE TITLE
Error when loading the pretrained cub model

### ISSUE THREAD

**Issue by XiSHEN0220** [dvl-tum/group_loss#1]
Hi, 

Thanks a lot for sharing the code!!!

I think there is an error on ` finetuned_cub_bn_inception.pth` .
I ran `python train.py --dataset_name cub` but got the following errors: 

```
size mismatch for last_linear.weight: copying a param with shape torch.Size([100, 1024]) from checkpoint, the shape in current model is torch.Size([98, 1024]).
size mismatch for last_linear.bias: copying a param with shape torch.Size([100]) from checkpoint, the shape in current model is torch.Size([98]).
```

I guess the model named ` finetuned_cub_bn_inception.pth` is actually the model of cars.

**Comment by XiSHEN0220** [comment]
Also, I am not able to run the command for the Cars dataset, which is shown in the [Readme](https://github.com/dvl-tum/group_loss#training). 

I got the following errors: 

  ```
File "train.py", line 174, in <module>
    for x, Y in dl_tr:
  File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 568, in __next__
    return self._process_next_batch(batch)
  File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xishen/group_loss/dataset/cub.py", line 37, in __getitem__
    im = self.transform(im)
  File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 42, in __call__
    img = t(img)
  File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 232, in __call__
    return self.lambd(img)
  File "/home/xishen/group_loss/dataset/utils.py", line 56, in <lambda>
    lambda x: x[[2, 1, 0], ...]
IndexError: index 2 is out of bounds for dimension 0 with size 1
```

It seems that the dataloader is only for the [CUB datasets](https://github.com/dvl-tum/group_loss/blob/master/data_utility.py#L10-L14), since it names as Birds? 

Could you provide more instruction?
Thanks a lot

**Comment by XiSHEN0220** [comment]
> Also, I am not able to run the command for the Cars dataset, which is shown in the [Readme](https://github.com/dvl-tum/group_loss#training).
> 
> I got the following errors:
> 
> ```
> File "train.py", line 174, in <module>
>   for x, Y in dl_tr:
> File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 568, in __next__
>   return self._process_next_batch(batch)
> File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
>   raise batch.exc_type(batch.exc_msg)
> IndexError: Traceback (most recent call last):
> File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
>   samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
>   samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/xishen/group_loss/dataset/cub.py", line 37, in __getitem__
>   im = self.transform(im)
> File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 42, in __call__
>   img = t(img)
> File "/home/xishen/grouplossPy36Torch11/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 232, in __call__
>   return self.lambd(img)
> File "/home/xishen/group_loss/dataset/utils.py", line 56, in <lambda>
>   lambda x: x[[2, 1, 0], ...]
> IndexError: index 2 is out of bounds for dimension 0 with size 1
> ```
> 
> It seems that the dataloader is only for the [CUB datasets](https://github.com/dvl-tum/group_loss/blob/master/data_utility.py#L10-L14), since it names as Birds?
> 
> Could you provide more instruction?
> Thanks a lot

Actually, in the raw Cars dataset, some images are in 'L' mode. 
That's why I had this error. 

I solved this pb by replacing this line [`im = PIL.Image.open(self.im_paths[index])`](https://github.com/dvl-tum/group_loss/blob/master/dataset/cub.py#L36) 
with 
`im = PIL.Image.open(self.im_paths[index]).convert('RGB')`
